In [10]:
# Dependencies
import numpy as np
import pandas as pd
import datetime as dt

# Python SQL toolkit and Object Relational Mapper
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func

In [2]:
engine = create_engine("sqlite:///hawaii.sqlite")

# reflect an existing database into a new model
Base = automap_base()
# reflect the tables
Base.prepare(engine, reflect=True)

# Save references to each table
Measurement = Base.classes.measurement
Station = Base.classes.station

In [29]:
session.query(Measurement.prcp).all()

[(0.08,),
 (0.0,),
 (0.0,),
 (0.0,),
 (None,),
 (0.06,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.01,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.01,),
 (0.0,),
 (0.04,),
 (0.12,),
 (0.0,),
 (None,),
 (0.03,),
 (0.01,),
 (None,),
 (0.01,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.02,),
 (0.01,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (None,),
 (0.03,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.01,),
 (0.0,),
 (0.0,),
 (0.12,),
 (0.08,),
 (0.03,),
 (0.0,),
 (0.43,),
 (0.06,),
 (None,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.06,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (None,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.01,),
 (0.17,),
 (0.15,),
 (0.27,),
 (0.01,),
 (0.0,),
 (0.01,),
 (0.0,),
 (0.01,),
 (0.01,),
 (0.0,),
 (0.0,),
 (0.01,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.04,),
 (0.01,),
 (0.0,),
 (0.02,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.03,),
 (0.2,),
 (0.08,),
 (0.01,),
 (0.0,),
 (0.05,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.03,),
 (0.0,),
 (0.0,),
 (0.0,),
 (None,),
 (0.0,),
 (0.05,),
 (0.0,),
 (0.0,),
 (0.02,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.01,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.02,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.01,),
 (0.05,),
 (0.09,),
 (0.05,),
 (0.06,),
 (0.08,),
 (0.08,),
 (0.03,),
 (0.06,),
 (0.09,),
 (0.0,),
 (0.0,),
 (0.0,),
 (None,),
 (0.02,),
 (0.0,),
 (0.04,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.02,),
 (0.04,),
 (0.01,),
 (0.02,),
 (0.07,),
 (0.08,),
 (0.03,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.01,),
 (0.0,),
 (0.05,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.01,),
 (0.0,),
 (0.04,),
 (0.03,),
 (0.0,),
 (0.04,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.02,),
 (0.04,),
 (0.01,),
 (0.0,),
 (0.0,),
 (0.06,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.05,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.04,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.57,),
 (0.31,),
 (0.03,),
 (0.0,),
 (0.06,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.07,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.07,),
 (0.05,),
 (0.06,),
 (0.03,),
 (0.02,),
 (0.0,),
 (0.01,),
 (0.01,),
 (None,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.23,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (None,),
 (0.03,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.04,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (1.58,),
 (0.77,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (1.4,),
 (0.0,),
 (0.0,),
 (None,),
 (0.13,),
 (0.55,),
 (0.06,),
 (0.01,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.01,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.09,),
 (None,),
 (0.03,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.03,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.22,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (1.29,),
 (1.3,),
 (0.0,),
 (0.29,),
 (None,),
 (0.0,),
 (0.04,),
 (0.05,),
 (0.0,),
 (0.0,),
 (1.72,),
 (0.0,),
 (0.82,),
 (0.0,),
 (0.2,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.1,),
 (0.0,),
 (0.0,),
 (0.88,),
 (0.4,),
 (0.03,),
 (None,),
 (0.2,),
 (0.15,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.01,),
 (0.05,),
 (0.01,),
 (0.02,),
 (0.0,),
 (0.02,),
 (0.0,),
 (0.06,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.04,),
 (0.0,),
 (0.0,),
 (0.05,),
 (0.04,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.09,),
 (1.11,),
 (0.36,),
 (0.02,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.12,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.04,),
 (0.0,),
 (0.0,),
 (2.1,),
 (0.02,),
 (0.12,),
 (0.12,),
 (0.55,),
 (0.55,),
 (0.02,),
 (0.11,),
 (0.1,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.01,),
 (0.0,),
 (0.0,),
 (0.06,),
 (0.02,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.05,),
 (0.07,),
 (0.0,),
 (0.56,),
 (0.89,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.03,),
 (0.01,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.05,),
 (0.06,),
 (0.07,),
 (None,),
 (0.0,),
 (0.0,),
 (0.01,),
 (0.01,),
 (0.0,),
 (0.05,),
 (0.02,),
 (0.0,),
 (0.0,),
 (0.01,),
 (0.01,),
 (0.01,),
 (0.0,),
 (0.03,),
 (0.02,),
 (0.0,),
 (0.0,),
 (0.15,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.04,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.03,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.04,),
 (0.09,),
 (0.04,),
 (0.12,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.02,),
 (0.03,),
 (0.01,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.02,),
 (0.0,),
 (0.0,),
 (0.07,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.05,),
 (0.1,),
 (0.02,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.03,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.01,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.02,),
 (0.04,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.03,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (None,),
 (0.0,),
 (0.03,),
 (0.0,),
 (0.0,),
 (0.02,),
 (0.03,),
 (0.0,),
 (0.0,),
 (0.03,),
 (0.02,),
 (0.0,),
 (0.02,),
 (0.01,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.14,),
 (1.6,),
 (0.01,),
 (0.0,),
 (0.05,),
 (0.01,),
 (0.0,),
 (0.03,),
 (0.58,),
 (0.28,),
 (0.02,),
 (0.01,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.02,),
 (0.0,),
 (0.05,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.01,),
 (0.02,),
 (0.01,),
 (0.0,),
 (0.01,),
 (0.02,),
 (0.07,),
 (0.0,),
 (0.0,),
 (0.02,),
 (0.03,),
 (0.08,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.13,),
 (0.07,),
 (0.07,),
 (0.08,),
 (0.4,),
 (0.7,),
 (0.0,),
 (0.01,),
 (0.07,),
 (0.02,),
 (0.15,),
 (0.02,),
 (0.18,),
 (0.03,),
 (0.04,),
 (0.1,),
 (0.03,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.01,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.04,),
 (0.0,),
 (0.0,),
 (0.02,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.04,),
 (0.03,),
 (1.03,),
 (0.01,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.37,),
 (0.28,),
 (0.01,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.04,),
 (0.01,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.04,),
 (0.01,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.05,),
 (0.06,),
 (0.0,),
 (0.0,),
 (0.06,),
 (0.0,),
 (0.03,),
 (0.01,),
 (1.08,),
 (4.0,),
 (2.42,),
 (0.02,),
 (0.19,),
 (0.06,),
 (0.0,),
 (0.03,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.05,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.03,),
 (0.01,),
 (0.0,),
 (0.0,),
 (0.11,),
 (0.03,),
 (0.02,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.19,),
 (0.0,),
 (0.03,),
 (0.0,),
 (0.07,),
 (0.05,),
 (0.06,),
 (0.0,),
 (0.03,),
 (0.0,),
 (0.01,),
 (0.01,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.01,),
 (0.04,),
 (0.03,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.04,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.01,),
 (0.02,),
 (0.02,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (None,),
 (None,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.03,),
 (0.15,),
 (0.01,),
 (0.0,),
 (0.05,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.04,),
 (0.01,),
 (0.03,),
 (0.0,),
 (0.04,),
 (0.0,),
 (None,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.01,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.02,),
 (0.0,),
 (0.0,),
 (0.01,),
 (0.01,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.02,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.01,),
 (0.0,),
 (0.0,),
 (None,),
 (None,),
 (0.0,),
 (0.0,),
 (0.03,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.02,),
 (1.0,),
 (0.02,),
 (0.04,),
 (0.0,),
 (0.01,),
 (0.04,),
 (0.06,),
 (0.0,),
 (0.01,),
 (0.04,),
 (0.0,),
 (0.06,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.02,),
 (0.05,),
 (0.04,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.06,),
 (0.0,),
 (0.07,),
 (0.08,),
 (0.0,),
 (0.04,),
 (0.0,),
 (0.0,),
 (0.01,),
 (0.02,),
 (0.0,),
 (0.0,),
 (0.02,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.03,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.02,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.02,),
 (0.04,),
 (0.0,),
 (0.02,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.03,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.06,),
 (0.0,),
 (0.08,),
 (0.03,),
 (0.01,),
 (0.03,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.0,),
 (0.02,),
 ...]

In [3]:
# Create our session (link) from Python to the DB
session = Session(engine)

## D1: Determine the Summary Statistics for June

In [7]:
# 1. Import the sqlalchemy extract function.
from sqlalchemy import extract

# 2. Write a query that filters the Measurement table to retrieve the temperatures for the month of June. 
temp_query_june = session.query(Measurement.date, Measurement.tobs).filter(extract('month', Measurement.date) == 6).all()

In [8]:
#  3. Convert the June temperatures to a list.
june_temps = list(temp_query_june)

In [16]:
# 4. Create a DataFrame from the list of temperatures for the month of June. 
june_df = pd.DataFrame(june_temps, columns=['Date', 'June Temperatures'])
june_df.set_index('Date', inplace=True)

In [19]:
# 5. Calculate and print out the summary statistics for the June temperature DataFrame.
june_df.describe()

       June Temperatures
count        1700.000000
mean           74.944118
std             3.257417
min            64.000000
25%            73.000000
50%            75.000000
75%            77.000000
max            85.000000

## D2: Determine the Summary Statistics for December

In [20]:
# 6. Write a query that filters the Measurement table to retrieve the temperatures for the month of December.
dec_query = session.query(Measurement.date, Measurement.tobs).filter(extract('month', Measurement.date) == 12).all()

In [21]:
# 7. Convert the December temperatures to a list.
dec_temps = list(dec_query)

In [22]:
# 8. Create a DataFrame from the list of temperatures for the month of December. 
dec_df = pd.DataFrame(dec_temps, columns=['Date', 'December Temperatures'])
dec_df.set_index('Date', inplace=True)

In [23]:
# 9. Calculate and print out the summary statistics for the Decemeber temperature DataFrame.
dec_df.describe()

       December Temperatures
count            1517.000000
mean               71.041529
std                 3.745920
min                56.000000
25%                69.000000
50%                71.000000
75%                74.000000
max                83.000000

## D3: Additional analysis of weather

In [31]:
june_query_prcp = session.query(Measurement.date, Measurement.prcp).filter(extract('month', Measurement.date)==6).all()
june_prcp = list(june_query_prcp)
june_prcp_df = pd.DataFrame(june_prcp, columns=['date', 'June Rainfall'])
june_prcp_df.set_index('date', inplace=True)
june_prcp_df.describe()

       June Rainfall
count    1574.000000
mean        0.136360
std         0.335731
min         0.000000
25%         0.000000
50%         0.020000
75%         0.120000
max         4.430000

In [32]:
dec_query_prcp = session.query(Measurement.date, Measurement.prcp).filter(extract('month', Measurement.date)==12).all()
dec_prcp = list(dec_query_prcp)
dec_prcp_df = pd.DataFrame(dec_prcp, columns=['date', 'December Rainfall'])
dec_prcp_df.set_index('date', inplace=True)
dec_prcp_df.describe()

       December Rainfall
count        1405.000000
mean            0.216819
std             0.541399
min             0.000000
25%             0.000000
50%             0.030000
75%             0.150000
max             6.420000